document.addEventListener('DOMContentLoaded',()=>{
  const languageButtons=[...document.querySelectorAll('[data-home-lang]')];
  const setLanguageMode=mode=>{const bilingual=mode!=='english';document.body.classList.toggle('english-only',!bilingual);languageButtons.forEach(button=>{const active=button.dataset.homeLang===(bilingual?'bilingual':'english');button.classList.toggle('active',active);button.setAttribute('aria-pressed',String(active))});localStorage.setItem('replica_site_language',bilingual?'bilingual':'english')};
  languageButtons.forEach(button=>button.addEventListener('click',()=>setLanguageMode(button.dataset.homeLang)));
  setLanguageMode(localStorage.getItem('replica_site_language')||'bilingual');
  const marathiNotes={travel:'विमानतळ, वाहन भाडे, बाहेरगावी प्रवास, तीर्थयात्रा, सफारी आणि समूह सहली.',banking:'मिनी बँक, आधार-पॅन, सरकारी सेवा, शेतकरी योजना, कार्ड आणि बिल सहाय्य.',printing:'झेरॉक्स, रंगीत प्रिंट, पासपोर्ट फोटो, स्कॅनिंग आणि लॅमिनेशन सेवा.',online:'शिक्षण, तिकीट व हॉटेल बुकिंग, व्यवसाय आणि वाहन कागदपत्र सहाय्य.'};
  Object.entries(marathiNotes).forEach(([type,copy])=>{const summary=document.querySelector(`.service-card.${type} .card-summary`);const description=summary?.querySelector('p');if(summary&&description&&!summary.querySelector('.mr-note')){const note=document.createElement('p');note.className='mr-note';note.lang='mr';note.textContent=copy;description.insertAdjacentElement('afterend',note)}});
  const loader=document.getElementById('hubLoader');
  const seen=sessionStorage.getItem('replica_loader_seen');
  setTimeout(()=>{loader?.classList.add('done');document.body.classList.remove('is-loading')},seen?280:1050);
  sessionStorage.setItem('replica_loader_seen','1');
  const menuButton=document.getElementById('menuButton'),menu=document.getElementById('mobileMenu');
  const setMenu=open=>{if(!menu)return;menu.hidden=!open;menuButton?.setAttribute('aria-expanded',String(open));menuButton?.setAttribute('aria-label',open?'Close menu':'Open menu')};
  menuButton?.addEventListener('click',()=>setMenu(menu.hidden));menu?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>setMenu(false)));document.addEventListener('click',e=>{if(!e.target.closest('.hub-header'))setMenu(false)});
  const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');io.unobserve(e.target)}}),{threshold:.1});document.querySelectorAll('.reveal').forEach(el=>io.observe(el));
  const toneSections=[['.hero','home'],['#services','services'],['#how','process'],['#about','community'],['#contact','contact']].map(([selector,tone])=>[document.querySelector(selector),tone]).filter(([element])=>element);
  const toneObserver=new IntersectionObserver(entries=>{const active=entries.filter(entry=>entry.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(active)document.body.dataset.pageTone=toneSections.find(([element])=>element===active.target)?.[1]||'home'},{rootMargin:'-28% 0px -48% 0px',threshold:[0,.2,.5]});toneSections.forEach(([element])=>toneObserver.observe(element));
  const sculpture=document.getElementById('brandSculpture');
  if(sculpture&&!matchMedia('(prefers-reduced-motion: reduce)').matches){sculpture.addEventListener('pointermove',event=>{if(innerWidth<=900)return;const box=sculpture.getBoundingClientRect();sculpture.style.setProperty('--tilt-x',`${((event.clientY-box.top)/box.height-.5)*-4}deg`);sculpture.style.setProperty('--tilt-y',`${((event.clientX-box.left)/box.width-.5)*5}deg`)});sculpture.addEventListener('pointerleave',()=>{sculpture.style.setProperty('--tilt-x','0deg');sculpture.style.setProperty('--tilt-y','0deg')})}
  const header=document.getElementById('hubHeader'),dock=document.getElementById('quickDock');let lastY=scrollY,timer;
  const showDock=()=>{dock?.classList.remove('dock-hidden');clearTimeout(timer);if(innerWidth<=640)timer=setTimeout(()=>dock?.classList.add('dock-hidden'),3200)};
  addEventListener('scroll',()=>{const y=Math.max(scrollY,0),up=y<lastY;header?.classList.toggle('hide',y>120&&!up);if(innerWidth<=640){if(up||y<100)showDock();else if(y>160)dock?.classList.add('dock-hidden')}lastY=y},{passive:true});dock?.addEventListener('pointerenter',showDock);dock?.addEventListener('focusin',showDock);showDock();
  const serviceCards=[...document.querySelectorAll('.service-card')];
  const setCard=(card,open)=>{const button=card.querySelector('.card-expand'),panel=card.querySelector('.service-list-panel');card.classList.toggle('expanded',open);button?.setAttribute('aria-expanded',String(open));if(button)button.querySelector('span').textContent=open?'Minimize services':button.dataset.closedLabel;if(button)button.querySelector('i').textContent=open?'−':'＋';panel?.setAttribute('aria-hidden',String(!open))};
  serviceCards.forEach((card,index)=>{const button=card.querySelector('.card-expand'),panel=card.querySelector('.service-list-panel');if(!button||!panel)return;const id=`service-list-${index+1}`;panel.id=id;button.setAttribute('aria-controls',id);button.dataset.closedLabel=button.querySelector('span').textContent;panel.setAttribute('aria-hidden','true');button.addEventListener('click',()=>{const willOpen=!card.classList.contains('expanded');serviceCards.forEach(other=>setCard(other,false));setCard(card,willOpen);if(willOpen&&innerWidth<=640)setTimeout(()=>card.scrollIntoView({behavior:'smooth',block:'start'}),180)})});
  const dialog=document.getElementById('helpDialog');document.querySelector('.help-trigger')?.addEventListener('click',()=>dialog?.showModal());document.getElementById('helpClose')?.addEventListener('click',()=>dialog?.close());dialog?.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});dialog?.querySelectorAll('[data-help]').forEach(b=>b.addEventListener('click',()=>{const message=`Namaskar Replica Click, I need help with: ${b.dataset.help}. Please guide me about the process and required documents.`;dialog.close();window.open(`https://wa.me/917276066532?text=${encodeURIComponent(message)}`,'_blank','noopener')}));
});
