import {bi,esc,request,travelCategory} from './catalog.js';
import {header,bindShell,dialog,bindDialog,showDialog,notice} from './shared.js';
const root=document.querySelector('#ownerApp');
let preview=false,tab='overview',records={},catalog=[],search='',loadError='',version=0;
const categories=()=>catalog.map(c=>[c.id,`${c.title} / ${c.titleMr||''}`]);
const f=(key,label,mr,type='text',required=false,options)=>({key,label,mr,type,required,options});
const specs={
  'custom':{title:'Services & pricing',mr:'सेवा आणि दर',endpoint:'service-groups?kind=custom',fields:[f('category_id','Service category','सेवा विभाग','select',true,categories),f('name_en','Service name in English','इंग्रजी सेवा नाव','text',true),f('name_mr','Service name in Marathi','मराठी सेवा नाव'),f('price','Display price','दाखवायचा दर'),f('price_note','Price note / unit','दराची नोंद / युनिट'),f('sort_order','Display order','दाखवण्याचा क्रम','number'),f('pinned','Feature this service','विशेष सेवा म्हणून दाखवा','checkbox'),f('visible','Show to customers','ग्राहकांना दाखवा','checkbox')]},
  'fleet':{title:'Vehicles',mr:'वाहने',endpoint:'fleet',fields:[f('name','Vehicle name','वाहनाचे नाव','text',true),f('seating','Seats','आसन संख्या'),f('price','Display fare','दाखवायचे भाडे'),f('features','Features','सुविधा'),f('image','Owner photo URL','मालकाच्या फोटोची URL','url'),f('display_mode','Vehicle display','वाहनाचे स्वरूप','select',false,[['3d','Illustration / प्रातिनिधिक चित्र'],['photo','Owner photograph / फोटो'],['auto','Illustration + photo option / दोन्ही']]),f('model_color','Illustration colour','चित्राचा रंग','color'),f('vehicle_type','Vehicle type','वाहन प्रकार','select',false,[['suv','SUV / MPV'],['sedan','Sedan'],['traveller','Traveller']]),f('visible','Show to customers','ग्राहकांना दाखवा','checkbox')]},
  'packages':{title:'Travel packages',mr:'प्रवास पॅकेजेस',endpoint:'packages',fields:[f('service','Package / service name','पॅकेज / सेवा नाव','text',true),f('vehicle','Vehicle','वाहन'),f('price','Display fare','दाखवायचे भाडे'),f('note','Included items / fare note','समाविष्ट सुविधा / दराची नोंद'),f('visible','Show to customers','ग्राहकांना दाखवा','checkbox')]},
  'groups':{title:'Service areas',mr:'सेवा विभाग',endpoint:'service-groups',fields:[f('id','Unique group ID','विभाग ID','text',true),f('slug','Page address','पानाचा पत्ता','text',true),f('title','English title','इंग्रजी शीर्षक','text',true),f('title_mr','Marathi title','मराठी शीर्षक'),f('description','English description','इंग्रजी वर्णन','textarea'),f('description_mr','Marathi description','मराठी वर्णन','textarea'),f('replica_ids','Included assistance categories','समाविष्ट सहाय्य विभाग','multiple',false,()=>categories().filter(c=>c[0]!=='travel')),f('include_tour','Include travel services','प्रवास सेवा समाविष्ट करा','checkbox'),f('color','Accent colour','रंग','color'),f('sort_order','Display order','दाखवण्याचा क्रम','number'),f('status','Publication status','प्रकाशन स्थिती','select',false,[['published','Published / प्रकाशित'],['draft','Draft / मसुदा']]),f('visible','Show to customers','ग्राहकांना दाखवा','checkbox')]},
  'gallery':{title:'Gallery',mr:'गॅलरी',endpoint:'gallery',fields:[f('title','Photo title','फोटो शीर्षक','text',true),f('src','Photo URL','फोटो URL','url',true),f('category','Category','विभाग'),f('visible','Show to customers','ग्राहकांना दाखवा','checkbox')]},
  'testimonials':{title:'Customer reviews',mr:'ग्राहकांचे अभिप्राय',endpoint:'testimonials',fields:[f('name','Customer name','ग्राहकाचे नाव','text',true),f('place','Route / service','मार्ग / सेवा'),f('text','Customer’s words','ग्राहकांचा अभिप्राय','textarea',true),f('rating','Rating (1–5)','गुण (१–५)','number',true),f('visible','Publish with customer permission','ग्राहकाच्या परवानगीने प्रकाशित करा','checkbox')]},
  'drivers':{title:'Driving team',mr:'चालक',endpoint:'drivers',fields:[f('legal_name','Full name (private)','संपूर्ण नाव (खाजगी)','text',true),f('display_name','Public display name','सार्वजनिक नाव','text',true),f('phone','Phone (private)','फोन (खाजगी)','tel'),f('languages','Languages','भाषा'),f('experience_years','Experience in years','अनुभव वर्षे','number'),f('eligible_vehicles','Eligible vehicles','पात्र वाहने'),f('photo_url','Photo URL','फोटो URL','url'),f('active_status','Availability','उपलब्धता','select',false,[['available','Available / उपलब्ध'],['assigned','Assigned / नियुक्त'],['unavailable','Unavailable / अनुपलब्ध']]),f('notes','Internal notes (private)','अंतर्गत नोंदी (खाजगी)','textarea')]}
};
const tabs=[['overview','◫','Overview','आढावा'],['custom','▤','Services & prices','सेवा आणि दर'],['groups','⊞','Service areas','सेवा विभाग'],['fleet','↗','Vehicles','वाहने'],['packages','₹','Travel packages','प्रवास पॅकेजेस'],['bookings','☷','Enquiry inbox','चौकशी'],['drivers','◎','Driving team','चालक'],['gallery','▧','Gallery','गॅलरी'],['testimonials','☆','Reviews','अभिप्राय'],['activity','◷','Activity log','नोंदी']];
function fieldHtml(field,value,editing){
  const {key,label,mr,type,required}=field;const opts=typeof field.options==='function'?field.options():field.options||[];const attrs=`name="${key}" ${required?'required':''} ${key==='id'&&editing?'readonly':''}`;
  if(type==='checkbox')return `<label class="check-label"><input ${attrs} type="checkbox" ${value?'checked':''}>${bi(label,mr)}</label>`;
  let input;
  if(type==='select'||type==='multiple'){input=`<select ${attrs} ${type==='multiple'?'multiple':''}>${opts.map(([id,name])=>`<option value="${esc(id)}" ${Array.isArray(value)?value.includes(id)?'selected':'':String(value)===id?'selected':''}>${esc(name)}</option>`).join('')}</select>${type==='multiple'?'<small>Ctrl/Cmd + click to select multiple categories.</small>':''}`;}
  else if(type==='textarea')input=`<textarea ${attrs} maxlength="600">${esc(value||'')}</textarea>`;
  else input=`<input ${attrs} type="${type}" value="${esc(value??(type==='color'?'#285b94':''))}" ${type==='number'?`min="${key==='rating'?1:0}" max="${key==='rating'?5:9999}" step="1"`:''} ${type==='url'?'placeholder="https://…"':''} ${type==='text'?'maxlength="120"':''}>`;
  return `<label class="${type==='textarea'||type==='multiple'?'wide':''}">${bi(label,mr)}${input}</label>`;
}
function endpoint(key,owner=false){if(key==='custom')return `/api/service-groups?kind=custom${owner?'&all=1':''}`;if(key==='groups')return '/api/service-groups';return `/api/${key}${owner&&['fleet','packages','gallery','testimonials'].includes(key)?'?all=1':''}`;}
async function start(){
  try{catalog=[travelCategory,...await request('/assets/data/replica-services.json')];}catch{catalog=[travelCategory];}
  try{const session=await request('/api/owner/session');if(session.authenticated){await workspace();return;}}catch{}
  login();
}
function login(error=''){
  root.innerHTML=header()+`<main id="ownerMain" class="owner-login"><section class="login-info"><div><span class="eyebrow" style="color:#ffa874">REPLICA CLICK · OWNER WORKSPACE</span><h1>${bi('Your business.<br>Your workspace.'.replace('<br>',' '),'तुमचा व्यवसाय. तुमचे व्यवस्थापन.')}</h1><p>${bi('Keep services, prices and travel options up to date. See new enquiries in one organised workspace.','सेवा, दर आणि प्रवास पर्याय अद्ययावत ठेवा. सर्व नवीन चौकशी एकाच ठिकाणी पहा.')}</p></div><p class="small">Replica Click + Ankit Tours & Travels<br>Kondhali, Nagpur</p></section><section class="login-form"><h2>${bi('Welcome back','पुन्हा स्वागत')}</h2><p class="muted small">${bi('Sign in with the owner PIN.','मालकाच्या PIN ने प्रवेश करा.')}</p><form id="loginForm"><label>${bi('Owner PIN','मालकाचा PIN')}<input name="pin" type="password" autocomplete="current-password" required maxlength="64"></label><p class="error-inline" id="loginError" role="alert">${esc(error)}</p><button class="button primary">${bi('Sign in →','प्रवेश करा →')}</button></form><p class="small muted">${bi('Exploring the redesign? Open a read-only sample workspace. It contains no private customer information.','नवीन रचना पाहायची आहे? फक्त पाहण्यासाठी नमुना कक्ष उघडा. त्यात ग्राहकांची खाजगी माहिती नाही.')}</p><button class="button" id="previewWorkspace">${bi('Preview the workspace','नमुना कक्ष पहा')}</button></section></main>`;bindShell();
  document.querySelector('#loginForm').onsubmit=async e=>{e.preventDefault();const button=e.target.querySelector('button');button.disabled=true;try{await request('/api/owner/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({pin:new FormData(e.target).get('pin')})});await workspace();}catch(err){document.querySelector('#loginError').textContent=err.message;}finally{button.disabled=false;}};
  document.querySelector('#previewWorkspace').onclick=async()=>{preview=true;await workspace();};
}
async function workspace(){
  root.innerHTML=header()+`${preview?'<div class="preview-banner"><span>READ-ONLY DESIGN PREVIEW · नमुना कक्ष · Sample records only. Changes and customer enquiries are disabled.</span><a href="/admin.html">Exit preview →</a></div>':''}<div class="owner-layout"><nav class="owner-nav" aria-label="Owner workspace"><span class="eyebrow">MANAGE YOUR CENTRE</span>${tabs.map(([id,icon,en,mr])=>`<button class="owner-tab" data-tab="${id}" ${tab===id?'aria-current="page"':''}><span aria-hidden="true">${icon}</span>${bi(en,mr)}</button>`).join('')}<div class="owner-side-note"><p>Replica Click<br>Ankit Tours & Travels</p><a class="text-link" href="/" target="_blank" rel="noopener">View public website ↗</a><button class="button small" id="signOut" style="margin-top:20px">${bi('Sign out','बाहेर पडा')}</button></div></nav><main id="ownerMain" class="owner-main"><p class="loading">Loading…</p></main></div>${dialog('editor','Edit','')}${dialog('confirmDelete','Confirm removal','')}${dialog('bookingDetail','Enquiry details','')}`;
  bindShell();document.querySelectorAll('dialog').forEach(bindDialog);document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;search='';render();});
  document.querySelector('#signOut').onclick=async()=>{if(preview){location.href='/admin.html';return;}try{await request('/api/owner/logout',{method:'POST'});location.href='/admin.html';}catch(err){notice('Sign out failed. Please retry. '+err.message);}};
  await load();render();
}
async function load(){
  const thisVersion=++version;loadError='';
  if(preview){const [seed,groups]=await Promise.all([request('/assets/data/site-data.json'),request('/assets/data/service-groups.json')]);records={...seed,groups:groups.map(g=>({...g,description:g.desc,replica_ids:g.replicaIds,include_tour:g.includeTour,visible:true,status:'published'})),custom:[],settings:[],bookings:[],drivers:[],activity:[]};return;}
  const keys=['fleet','packages','gallery','testimonials','groups','custom','drivers','bookings'];
  const values=await Promise.allSettled(keys.map(key=>request(endpoint(key,true))));
  if(thisVersion!==version)return;
  values.forEach((res,i)=>{if(res.status==='fulfilled'&&Array.isArray(res.value))records[keys[i]]=res.value;else{records[keys[i]]=[];loadError+=`${keys[i]} could not be loaded. `;}});
  try{records.settings=await request('/api/service-settings');}catch{records.settings=[];loadError+='Service prices could not be loaded. ';}
  try{const log=await request('/api/audit');records.activity=log.rows||[];}catch{records.activity=[];loadError+='Activity history unavailable. ';}
}
const visible=row=>row.visible!==false&&row.status!=='draft';
function render(){
  document.querySelectorAll('[data-tab]').forEach(b=>{if(b.dataset.tab===tab)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});
  const [,icon,en,mr]=tabs.find(t=>t[0]===tab);const main=document.querySelector('#ownerMain');
  main.innerHTML=`<div class="owner-heading"><div><span class="eyebrow">OWNER WORKSPACE / मालक कक्ष</span><h1>${bi(en,mr)}</h1><p class="muted small">${preview?'Sample content · Read-only preview':'Published changes appear on the public website after saving.'}</p></div><div class="owner-actions"><button class="button" id="exportWorkspace" ${preview||loadError?'disabled':''}>Export JSON</button><button class="button" id="refresh">↻ ${bi('Refresh','पुन्हा लोड')}</button>${specs[tab]?`<button class="button primary" id="addRecord" ${preview?'disabled':''}>+ ${bi('Add new','नवीन जोडा')}</button>`:''}</div></div>${loadError?`<p class="form-note error-inline" role="alert">${esc(loadError)} Retry before editing incomplete lists.</p>`:''}<div id="ownerContent"></div><p class="owner-footer">${bi('Keep public information accurate. Customer details and internal driver notes stay in the owner workspace.','सार्वजनिक माहिती अचूक ठेवा. ग्राहक माहिती आणि चालकांच्या अंतर्गत नोंदी मालक कक्षात राहतात.')}</p>`;
  document.querySelector('#refresh').onclick=async()=>{await load();render();notice(loadError||'Workspace refreshed / कक्ष अद्ययावत');};document.querySelector('#addRecord')?.addEventListener('click',()=>editRecord(tab));
  document.querySelector('#exportWorkspace').onclick=()=>{if(preview||loadError)return;const blob=new Blob([JSON.stringify(records,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download='replica-owner-export.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
  const area=document.querySelector('#ownerContent');
  if(tab==='overview'){area.innerHTML=overview();area.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{tab=b.dataset.go;render();});return;}
  if(tab==='activity'){area.innerHTML=`<section class="workspace-panel"><h2>${bi('Recent owner activity','मालकाच्या अलीकडील नोंदी')}</h2><p class="muted small">Latest 50 events: sign-ins, sign-outs and content changes.</p><div class="activity-list">${(records.activity||[]).map(x=>`<div class="activity-row"><div><b>${esc(x.event_type)}</b> · ${esc(x.entity_type)} ${esc(x.entity_id)}</div><span>${esc(new Date(x.created_at).toLocaleString())}</span></div>`).join('')||'<p class="empty">No activity to display.</p>'}</div></section>`;return;}
  area.innerHTML=`<div class="owner-search"><input type="search" id="ownerSearch" placeholder="Search this section / या विभागात शोधा" aria-label="Search this section" value="${esc(search)}"></div><div id="ownerRows"></div>`;
  renderRows();document.querySelector('#ownerSearch').oninput=e=>{search=e.target.value;renderRows();};
}
function overview(){const metrics=[['banking',(records.custom||[]).filter(visible).length,'Owner-created services'],['travel',(records.fleet||[]).filter(visible).length,'Vehicles visible'],['online',(records.bookings||[]).filter(b=>b.status==='new').length,'New enquiries'],['printing',(records.groups||[]).filter(visible).length,'Service areas visible']];return `<div class="owner-metrics">${metrics.map(([tone,n,label])=>`<article class="metric ${tone}"><strong>${n}</strong><span>${label}</span></article>`).join('')}</div><section class="workspace-panel"><h2>${bi('What would you like to update?','तुम्हाला काय बदलायचे आहे?')}</h2><div class="owner-quick-grid"><button data-go="custom"><strong>${bi('Services & charges','सेवा आणि शुल्क')}</strong><span>Add services, change a price, pin or hide a service.</span></button><button data-go="fleet"><strong>${bi('Vehicles & fares','वाहने आणि भाडे')}</strong><span>Add a vehicle, change its illustration or upload a photo URL.</span></button><button data-go="bookings"><strong>${bi('Customer enquiries','ग्राहक चौकशी')}</strong><span>Read requirements and move an enquiry through its status.</span></button></div></section><section class="workspace-panel"><h2>${bi('How publishing works','प्रकाशन कसे होते')}</h2><div class="grid three"><div><b>01 · Edit</b><p class="small muted">Use the labelled form and preview the public card.</p></div><div><b>02 · Choose visibility</b><p class="small muted">Keep “Show to customers” off while preparing an item.</p></div><div><b>03 · Save</b><p class="small muted">Saving writes the selected visibility and records the change.</p></div></div></section>`;}
function table(rows,columns){return `<div class="table-wrap"><table class="owner-table"><thead><tr>${columns.map(c=>`<th scope="col">${c}</th>`).join('')}</tr></thead><tbody>${rows.join('')||`<tr><td colspan="${columns.length}"><div class="empty">${bi('No records to display.','दाखवण्यासाठी नोंदी नाहीत.')}</div></td></tr>`}</tbody></table></div>`;}
function actionButtons(key,row){return `<div class="actions"><button class="button small" data-edit="${key}" data-id="${esc(row.id)}" ${preview?'disabled':''}>Edit</button>${key!=='drivers'?`<button class="button small" data-visibility="${key}" data-id="${esc(row.id)}" ${preview?'disabled':''}>${visible(row)?'Hide':'Show'}</button>`:''}<button class="button small" data-delete="${key}" data-id="${esc(row.id)}" ${preview?'disabled':''} aria-label="Delete ${esc(row.name||row.name_en||row.title||row.service||row.display_name)}">×</button></div>`;}
function renderRows(){
  const host=document.querySelector('#ownerRows');const matching=row=>Object.values(row).join(' ').toLowerCase().includes(search.toLowerCase());
  if(tab==='bookings')host.innerHTML=table((records.bookings||[]).filter(matching).map(b=>`<tr><td><b>${esc(b.name)}</b><span class="sub">${esc(b.phone)}</span></td><td>${esc(b.service)}<span class="sub">${esc(b.date)}</span></td><td><span class="status ${esc(b.status)}">${esc(b.status)}</span></td><td><button class="button small" data-booking="${esc(b.id)}">Read enquiry →</button></td></tr>`),['Customer','Service','Status','Action']);
  else{const key=tab;host.innerHTML=table((records[key]||[]).filter(matching).map(row=>`<tr><td><b>${esc(row.name_en||row.name||row.title||row.service||row.display_name||row.legal_name)}</b><span class="sub">${esc(row.name_mr||row.title_mr||row.category_id||row.vehicle||row.seating||'')}</span></td><td>${esc(row.price||row.languages||row.status||'—')}${row.pinned?'<span class="sub">★ Featured</span>':''}</td><td><span class="status ${key==='drivers'?'':visible(row)?'on':'off'}">${esc(key==='drivers'?row.active_status:visible(row)?'Visible':'Hidden / draft')}</span></td><td>${actionButtons(key,row)}</td></tr>`),['Name','Details','Public status','Actions']);}
  if(tab==='custom'){
    const settings=new Map((records.settings||[]).map(s=>[s.service_id,s]));
    const items=catalog.flatMap(c=>c.items.map((name,i)=>({service_id:`${c.id}-${i+1}`,name,mr:c.itemsMr?.[i],...settings.get(`${c.id}-${i+1}`)}))).filter(matching);
    host.innerHTML=`<h2 style="font-size:1.15rem">${bi('Owner-created services','मालकाने जोडलेल्या सेवा')}</h2>${host.innerHTML}<h2 style="font-size:1.15rem;margin-top:30px">${bi('Built-in service prices & visibility','मूळ सेवांचे दर आणि दृश्यता')}</h2><p class="small muted">${bi('Add a price such as ₹2 / page. Leave it blank when charges need confirmation.','₹२ / पान असा दर द्या. खात्री करायची असल्यास दर रिकामा ठेवा.')}</p>${table(items.map(i=>`<tr><td>${bi(i.name,i.mr)}</td><td>${esc(i.price||'Ask for charges')}<span class="sub">${esc(i.price_note)}</span></td><td><span class="status ${i.visible===false?'off':'on'}">${i.visible===false?'Hidden':'Visible'}</span>${i.pinned?' ★':''}</td><td><button class="button small" data-setting="${esc(i.service_id)}" ${preview?'disabled':''}>Edit price & display</button></td></tr>`),['Service','Price','Status','Action'])}`;
  }
  host.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editRecord(b.dataset.edit,(records[b.dataset.edit]||[]).find(r=>String(r.id)===b.dataset.id)));
  host.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>deleteRecord(b.dataset.delete,(records[b.dataset.delete]||[]).find(r=>String(r.id)===b.dataset.id)));
  host.querySelectorAll('[data-visibility]').forEach(b=>b.onclick=async()=>{if(preview)return;const row=records[b.dataset.visibility].find(r=>String(r.id)===b.dataset.id);try{b.disabled=true;await mutate(b.dataset.visibility,'PUT',{...row,visible:!visible(row),...(row.status==='draft'?{status:'published'}:{})});await load();renderRows();notice('Visibility updated');}catch(err){notice(err.message);b.disabled=false;}});
  host.querySelectorAll('[data-setting]').forEach(b=>b.onclick=()=>editSetting(b.dataset.setting));host.querySelectorAll('[data-booking]').forEach(b=>b.onclick=()=>readBooking(records.bookings.find(r=>String(r.id)===b.dataset.booking)));
}
async function mutate(key,method,body,id){if(preview)throw new Error('Read-only preview');let url=endpoint(key);if(id)url+=`${url.includes('?')?'&':'?'}id=${encodeURIComponent(id)}`;return request(url,{method,headers:{'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});}
function editRecord(key,row){if(preview)return;const spec=specs[key];const model=row||{visible:false,pinned:false,status:'draft',sort_order:0,model_color:'#cb5627',color:'#285b94',rating:5,replica_ids:[],display_mode:'3d',active_status:'unavailable'};const node=document.querySelector('#editor');node.querySelector('h2').innerHTML=bi(`${row?'Edit':'Add'} ${spec.title}`,spec.mr);node.querySelector('.dialog-body').innerHTML=`<form id="editorForm"><div class="editor-grid">${spec.fields.map(field=>fieldHtml(field,model[field.key],!!row)).join('')}</div><div class="editor-preview"><span class="eyebrow">PUBLIC CARD PREVIEW / सार्वजनिक स्वरूप</span><h3 id="cardPreviewName"></h3><p id="cardPreviewDetail" class="muted small"></p></div><p class="form-note">${bi('Saving publishes the selected visibility immediately. Keep visibility off to prepare an item privately.','जतन केल्यावर निवडलेली दृश्यता लगेच लागू होईल. खाजगी तयारीसाठी दृश्यता बंद ठेवा.')}</p><p id="editorError" class="error-inline" role="alert"></p><div class="form-actions"><button type="button" class="button" data-close>Cancel / रद्द करा</button><button class="button primary" type="submit">Save changes / बदल जतन करा</button></div></form>`;
  const form=node.querySelector('form');function previewCard(){const fd=new FormData(form);node.querySelector('#cardPreviewName').textContent=fd.get('name_en')||fd.get('name')||fd.get('title')||fd.get('service')||fd.get('display_name')||'Your item';node.querySelector('#cardPreviewDetail').textContent=[fd.get('name_mr')||fd.get('title_mr'),fd.get('price'),fd.get('price_note'),fd.get('visible')?'Visible to customers':'Hidden from public'].filter(Boolean).join(' · ');}form.addEventListener('input',previewCard);previewCard();
  form.onsubmit=async event=>{event.preventDefault();const fd=new FormData(form);const payload={...row};for(const field of spec.fields)payload[field.key]=field.type==='checkbox'?fd.has(field.key):field.type==='multiple'?fd.getAll(field.key):field.type==='number'?Number(fd.get(field.key)||0):String(fd.get(field.key)||'').trim();
    if(key==='groups'&&(!/^[a-z0-9-]+$/.test(payload.id)||!/^[a-z0-9-]+$/.test(payload.slug))){node.querySelector('#editorError').textContent='Group ID and address must use lowercase letters, digits and hyphens.';return;}
    if(key==='fleet'&&payload.display_mode==='photo'&&!payload.image){node.querySelector('#editorError').textContent='Add a photo URL or choose Illustration.';return;}
    for(const field of spec.fields.filter(f=>f.type==='url'))if(payload[field.key]&&!payload[field.key].startsWith('https://')){node.querySelector('#editorError').textContent='Use an HTTPS image URL.';return;}
    const submit=form.querySelector('[type=submit]');submit.disabled=true;try{await mutate(key,row?'PUT':'POST',payload);node.close();await load();render();notice('Saved / जतन केले');}catch(err){node.querySelector('#editorError').textContent=err.message;}finally{submit.disabled=false;}};showDialog(node);
}
function editSetting(id){
  if(preview)return;const current=(records.settings||[]).find(s=>s.service_id===id)||{service_id:id,visible:true,pinned:false,price:'',price_note:''};const node=document.querySelector('#editor');node.querySelector('h2').innerHTML=bi('Price & public display','दर आणि सार्वजनिक दृश्यता');node.querySelector('.dialog-body').innerHTML=`<form id="settingForm"><div class="editor-grid">${[f('price','Display price','दाखवायचा दर'),f('price_note','Unit / price note','युनिट / दराची नोंद'),f('pinned','Feature this service','विशेष सेवा','checkbox'),f('visible','Show to customers','ग्राहकांना दाखवा','checkbox')].map(field=>fieldHtml(field,current[field.key])).join('')}</div><p class="form-note">Service ID: ${esc(id)}. Use a clear unit, e.g. ₹2 / A4 page, black & white.</p><p class="error-inline" id="settingError" role="alert"></p><div class="form-actions"><button type="button" class="button" data-close>Cancel</button><button class="button primary">Save display settings</button></div></form>`;
  node.querySelector('form').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.target);const btn=e.target.querySelector('.primary');btn.disabled=true;try{await request('/api/service-settings',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({...current,price:fd.get('price'),price_note:fd.get('price_note'),pinned:fd.has('pinned'),visible:fd.has('visible')})});node.close();await load();render();notice('Price and visibility saved');}catch(err){node.querySelector('#settingError').textContent=err.message;}finally{btn.disabled=false;}};showDialog(node);
}
function deleteRecord(key,row){if(preview||!row)return;const node=document.querySelector('#confirmDelete');node.querySelector('.dialog-body').innerHTML=`<p class="delete-warning">Remove “${esc(row.name||row.name_en||row.title||row.service||row.display_name)}”?</p><p>This permanently removes the record. Use Hide if you may need it again.</p><p id="deleteError" class="error-inline" role="alert"></p><div class="form-actions"><button class="button" data-close>Keep record</button><button class="button orange" id="confirmRemoval">Remove record</button></div>`;node.querySelector('#confirmRemoval').onclick=async e=>{e.target.disabled=true;try{await mutate(key,'DELETE',null,row.id);node.close();await load();render();notice('Record removed');}catch(err){node.querySelector('#deleteError').textContent=err.message;e.target.disabled=false;}};showDialog(node);}
function readBooking(row){const node=document.querySelector('#bookingDetail');node.querySelector('.dialog-body').innerHTML=`<h3>${esc(row.name)}</h3><p>${esc(row.phone)} · ${esc(row.service)}</p><pre class="booking-message"></pre><label>Status<select id="bookingStatus" ${preview?'disabled':''}>${['new','confirmed','done','cancelled'].map(s=>`<option ${row.status===s?'selected':''}>${s}</option>`).join('')}</select></label><p class="error-inline" id="bookingError" role="alert"></p><div class="form-actions"><a class="button" href="tel:${esc(row.phone.replace(/[^+0-9]/g,''))}">Call customer</a><button class="button primary" id="saveBookingStatus" ${preview?'disabled':''}>Save status</button></div>`;node.querySelector('pre').textContent=row.message||'No additional requirements.';node.querySelector('#saveBookingStatus').onclick=async e=>{e.target.disabled=true;try{await mutate('bookings','PUT',{id:row.id,status:node.querySelector('select').value});node.close();await load();render();notice('Enquiry updated');}catch(err){node.querySelector('#bookingError').textContent=err.message;e.target.disabled=false;}};showDialog(node);}
start().catch(error=>{root.innerHTML=header()+`<main class="wrap section" id="ownerMain"><h1>Workspace unavailable</h1><p>${esc(error.message)}</p><a class="button" href="/admin.html">Try again</a></main>`;bindShell();});
